export default {
  locale: 'en',
  messages: {
    siteTitle: 'Dental clinic',
    HomeBannerSlogan: 'welcome  to  <span>dental </span>clinic<br />the <span>best</span>quality<br /><span>treatment</span>.',
    addService: 'Add Service',
    addTestimonial: 'Add Testimonial',
    addPatient: 'Add Patient',
    addMedicalTreatment: 'Add medical treatment',
    switchLanguage: 'Switch Language',
    readMore: 'Read more',
    serviceLabel: 'Services',
    patientLabel: 'Patients',
    testimonialLabel: 'Testimonials',
    medicalTreatmentLabel: 'Medical treatment',
    appointmentLabel: 'Take an appointment',
    homeLabel: 'Home',
    by: 'By',
    editService: 'Edit Service',
    deleteService: 'Delete Service',
    createNewService: 'Create new service',
    editTheService: 'Edit the service',
    editTestimonial: 'Edit testimonial',
    deleteTestimonial: 'Delete testimonial',
    createNewTestimonial: 'Create new testimonial',
    editTheTestimonial: 'Edit the testimonial',
    editPatient: 'Edit patient',
    deletePatient: 'Delete patient',
    createNewPatient: 'Create new patient',
    editThePatient: 'Edit the patient',
    medicalTreatmentTitle: 'Title',
    medicalTreatmentContent: 'Content',
    editMedicalTreatment: 'Edit medical treatment',
    deleteMedicalTreatment: 'Delete medical treatment',
    createNewMedicalTreatment: 'Create new medical treatment',
    editTheMedicalTreatment: 'Edit the medical treatment',
    medicalTreatmentCost: 'Cost',
    authorName: "Author's Name",
    serviceTitle: 'Service Title',
    serviceContent: 'Service Content',
    patientFirstName: 'FirstName',
    patientLastName: 'LastName',
    patientSex: 'Sex',
    patientBirthDay: 'BirthDay',
    patientPhone: 'Phone',
    patientEmail: 'Email',
    patientAddress: 'Address',
    patientCity: 'City',
    patientMaritalStatus: 'MaritalStatus',
    patientCompany: 'Company',
    patientDoctor: 'Doctor',
    patientInsurance: 'Insurance',
    appointmentReason: 'Reason',
    appointmentList: 'Appointment list',
    appointmentDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac turpis a orci placerat ornare in eget odio. Ut vitae venenatis metus. Aliquam metus sapien, vulputate eu erat vitae, elementum lacinia erat. Mauris nec iaculis mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    submittedAppointmentMsg: 'Your appointment has been validated, thank you for coming on time',
    createAnAccount: 'Create an account',
    blockTheAccount: 'Block the account',
    unblockTheAccount: 'Unblock the account',
    addCMSPage: 'Add a CMS page',
    cmsPageLabel: 'CMS pages',
    editCMSPage: 'Edit the CMS page',
    deleteCMSPage: 'Delete the CMS page',
    createNewCMSPage: 'Add a new the CMS page',
    editTheCMSPage: 'Edit the CMS page',
    create: 'create',
    update: 'Update',
    delete: 'Delete',
    submit: 'Submit',
    title: 'Title',
    content: 'Content',
    password: 'Password',
    username: 'User name',
    logout: 'logout',
    accessYourAccount: 'Access your account',
    welcome: 'Welcome',
    aboutUsSummary: `The Dr.AMGHAR orthodontic center is a medical area dedicated to oral health but also to the improvement and establishment of dental aesthetics and smiles.
      On the firm's website you will find advice and explanations on dental health: prevention is the best way to keep healthy teeth.`,
    aboutUsContent: `"Dr. AMGHAR has been an exclusive orthodontist since 2006. She worked at Ibn Rochd University as a specialist in orthodontics in addition to supervising students in the practical work of ODF and cephalometry, as well as supervising dentists registered in the DU. orthodontics of the faculty of dentistry - RABAT.
      With a constant focus on continuing education, Dr. AMGHAR attended several national and international seminars and conferences. She has also participated as a speaker in numerous conferences and scientific events.
      The DR AMGHAR orthodontic practice, which is located in Rabat, offers you quality care in a pleasant setting. The orthodontist Dr. AMGHAR accompanies you for orthopedic orthopedic or orthodontic care for children, adult orthodontics.
      Call 05 22 86 23 22 for an appointment with our specialists
      The orthodontist Dr. AMGHAR accompanies you daily for good oral health and care in specialties: orthodontics and pedodontics. Our team of experts is ready to welcome you and provide you with the most appropriate treatments: pedodontics, orthodontics, dental aesthetics, radiology ...\`
      The Orthodontist Dr. AMGHAR specializes in orthodontics, is open Monday to Friday 9am to 19H and Saturday from 9H to 13H.`,
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	}`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	}`,
    nestedDateComment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	} as of {date}`,
    emptyCollectionMessage:
      'No result found, try to insert a new {collection}.',
    appRights: '(C) 2018 All rights reserved ',
  },
};
