export default {
  locale: 'en',
  messages: {
    siteTitle: 'Dental clinic',
    addService: 'Add Service',
    addTestimonial: 'Add Testimonial',
    addPatient: 'Add Patient',
    addMedicalTreatment: 'Add medical treatment',
    switchLanguage: 'Switch Language',
    readMore: 'Read more',
    serviceLabel: 'Services',
    patientLabel: 'Patients',
    testimonialLabel: 'Testimonials',
    medicalTreatmentLabel: 'Medical treatment',
    appointmentLabel: 'Take an appointment',
    homeLabel: 'Home',
    by: 'By',
    editService: 'Edit Service',
    deleteService: 'Delete Service',
    createNewService: 'Create new service',
    editTheService: 'Edit the service',
    editTestimonial: 'Edit testimonial',
    deleteTestimonial: 'Delete testimonial',
    createNewTestimonial: 'Create new testimonial',
    editTheTestimonial: 'Edit the testimonial',
    editPatient: 'Edit patient',
    deletePatient: 'Delete patient',
    createNewPatient: 'Create new patient',
    editThePatient: 'Edit the patient',
    medicalTreatmentTitle: 'Title',
    medicalTreatmentContent: 'Content',
    editMedicalTreatment: 'Edit medical treatment',
    deleteMedicalTreatment: 'Delete medical treatment',
    createNewMedicalTreatment: 'Create new medical treatment',
    editTheMedicalTreatment: 'Edit the medical treatment',
    medicalTreatmentCost: 'Cost',
    authorName: "Author's Name",
    serviceTitle: 'Service Title',
    serviceContent: 'Service Content',
    patientFirstName: 'FirstName',
    patientLastName: 'LastName',
    patientSex: 'Sex',
    patientBirthDay: 'BirthDay',
    patientPhone: 'Phone',
    patientEmail: 'Email',
    patientAddress: 'Address',
    patientCity: 'City',
    patientMaritalStatus: 'MaritalStatus',
    patientCompany: 'Company',
    patientDoctor: 'Doctor',
    patientInsurance: 'Insurance',
    appointmentReason: 'Reason',
    appointmentList: 'Appointment list',
    appointmentDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac turpis a orci placerat ornare in eget odio. Ut vitae venenatis metus. Aliquam metus sapien, vulputate eu erat vitae, elementum lacinia erat. Mauris nec iaculis mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    submittedAppointmentMsg: 'Your appointment has been validated, thank you for coming on time',
    create: 'create',
    update: 'Update',
    delete: 'Delete',
    submit: 'Submit',
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	}`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	}`,
    nestedDateComment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	} as of {date}`,
    emptyCollectionMessage:
      'No result found, try to insert a new {collection}.',
    appRights: '(C) 2018 All rights reserved ',
  },
};
