export default {
  locale: 'fr',
  messages: {
    siteTitle: 'Cabinet dentaire',
    addService: 'Ajouter un service',
    addPatient: 'Add Patient',
    addTestimonial: 'Ajouter un témoignage',
    addMedicalTreatment: 'Add medical treatment',
    switchLanguage: 'Changer de langue',
    readMore: 'Lire plus',
    serviceLabel: 'Services',
    patientLabel: 'Patients',
    testimonialLabel: 'Témoignages',
    medicalTreatmentLabel: 'Medical treatment',
    appointmentLabel: 'Prendre un rendez-vous',
    homeLabel: 'Page d\'accueil',
    by: 'Par',
    editService: 'Modifer le service',
    deleteService: 'Supprimer le service',
    createNewService: 'Créer un nouveau service',
    editTheService: 'Modfier le service',
    editTestimonial: 'Modifer le témoignage',
    deleteTestimonial: 'Supprimer le témoignage',
    createNewTestimonial: 'Créer un témoignage',
    editTheTestimonial: 'Edit the testimonial',
    editPatient: 'Edit patient',
    deletePatient: 'Delete patient',
    createNewPatient: 'Create new patient',
    editThePatient: 'Edit the patient',
    medicalTreatmentTitle: 'Title',
    medicalTreatmentContent: 'Content',
    editMedicalTreatment: 'Edit medical treatment',
    deleteMedicalTreatment: 'Delete medical treatment',
    createNewMedicalTreatment: 'Create new medical treatment',
    editTheMedicalTreatment: 'Edit the medical treatment',
    medicalTreatmentCost: 'Prix',
    authorName: 'Nom de l\'auteur',
    serviceTitle: 'Titre de service',
    serviceContent: 'Contenu après',
    patientFirstName: 'FirstName',
    patientLastName: 'LastName',
    patientSex: 'Sex',
    patientBirthDay: 'BirthDay',
    patientPhone: 'Phone',
    patientEmail: 'Email',
    patientAddress: 'Address',
    patientCity: 'City',
    patientMaritalStatus: 'MaritalStatus',
    patientCompany: 'Company',
    patientDoctor: 'Doctor',
    patientInsurance: 'Insurance',
    appointmentReason: 'Reason',
    appointmentList: 'Liste de rendez-vous',
    appointmentDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac turpis a orci placerat ornare in eget odio. Ut vitae venenatis metus. Aliquam metus sapien, vulputate eu erat vitae, elementum lacinia erat. Mauris nec iaculis mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    submittedAppointmentMsg: 'Votre prise de rendez-vous à été validé, merci de venir à l\'heure',
    create: 'create',
    update: 'Update',
    delete: 'Delete',
    submit: 'Soumettre',
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	} (in real app this would be translated to French)`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	} (in real app this would be translated to French)`,
    nestedDateComment: `user {name} {value, plural,
  		  =0 {does not have any comments}
  		  =1 {has # comment}
  		  other {has # comments}
  		} as of {date} (in real app this would be translated to French)`,
    emptyCollectionMessage: 'No result found, try to insert a new {collection}.',
    appRights: '(C) 2018 tous droits réservés ',
  },
};
