export default {
  locale: 'fr',
  messages: {
    siteTitle: 'Cabinet dentaire',
    HomeBannerSlogan: 'bienvenue  au  <span>dental clinic</span><br />le meilleur traitement de<br /><span>qualité.</span>',
    addService: 'Ajouter un service',
    addPatient: 'Add Patient',
    addTestimonial: 'Ajouter un témoignage',
    addMedicalTreatment: 'Add medical treatment',
    switchLanguage: 'Changer de langue',
    readMore: 'Lire plus',
    serviceLabel: 'Services',
    patientLabel: 'Patients',
    testimonialLabel: 'Témoignages',
    medicalTreatmentLabel: 'Medical treatment',
    appointmentLabel: 'Prendre un rendez-vous',
    homeLabel: 'Page d\'accueil',
    by: 'Par',
    editService: 'Modifer le service',
    deleteService: 'Supprimer le service',
    createNewService: 'Créer un nouveau service',
    editTheService: 'Modfier le service',
    editTestimonial: 'Modifer le témoignage',
    deleteTestimonial: 'Supprimer le témoignage',
    createNewTestimonial: 'Créer un témoignage',
    editTheTestimonial: 'Edit the testimonial',
    editPatient: 'Edit patient',
    deletePatient: 'Delete patient',
    createNewPatient: 'Create new patient',
    editThePatient: 'Edit the patient',
    medicalTreatmentTitle: 'Title',
    medicalTreatmentContent: 'Content',
    editMedicalTreatment: 'Edit medical treatment',
    deleteMedicalTreatment: 'Delete medical treatment',
    createNewMedicalTreatment: 'Create new medical treatment',
    editTheMedicalTreatment: 'Edit the medical treatment',
    medicalTreatmentCost: 'Prix',
    authorName: 'Nom de l\'auteur',
    serviceTitle: 'Titre de service',
    serviceContent: 'Contenu après',
    patientFirstName: 'FirstName',
    patientLastName: 'LastName',
    patientSex: 'Sex',
    patientBirthDay: 'BirthDay',
    patientPhone: 'Phone',
    patientEmail: 'Email',
    patientAddress: 'Address',
    patientCity: 'City',
    patientMaritalStatus: 'MaritalStatus',
    patientCompany: 'Company',
    patientDoctor: 'Doctor',
    patientInsurance: 'Insurance',
    appointmentReason: 'Reason',
    appointmentList: 'Liste de rendez-vous',
    appointmentDescription: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ac turpis a orci placerat ornare in eget odio. Ut vitae venenatis metus. Aliquam metus sapien, vulputate eu erat vitae, elementum lacinia erat. Mauris nec iaculis mi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.',
    submittedAppointmentMsg: 'Votre prise de rendez-vous à été validé, merci de venir à l\'heure',
    createAnAccount: 'Créer un compte',
    blockTheAccount: 'Bloquer le compte',
    unblockTheAccount: 'Débloquer le compte',
    addCMSPage: 'Add a CMS page',
    cmsPageLabel: 'Les pages CMS',
    editCMSPage: 'Modifier la page CMS',
    deleteCMSPage: 'Supprimer la page CMS',
    createNewCMSPage: 'Créer une nouvelle page CMS',
    editTheCMSPage: 'Modifier la page',
    create: 'create',
    update: 'Update',
    delete: 'Delete',
    title: 'Titre',
    content: 'Contenu',
    submit: 'Soumettre',
    password: 'Le mot de passe',
    username: 'Le nom d\'utilisateur',
    logout: 'Se déconnecter',
    accessYourAccount: 'Se connecter',
    welcome: 'Bienvenue',
    aboutUsSummary: 'Le centre d’orthodontie de Dr.AMGHAR un espace médical  réservé à la santé bucco-dentaire mais aussi à l’amélioration et l’établissement de l’esthétique dentaire et du sourire. Sur le site internet du cabinet vous trouverez des conseils et des explications sur la santé dentaire : la prévention est le meilleur moyen de conserver des dents saines.',
    aboutUsContent: `« Dr AMGHAR est orthodontiste exclusive depuis 2006. elle a exercé au CHU Ibn Rochd comme spécialiste en orthodontie parallèlement à l’encadrement des étudiants aux travaux pratiques d’ODF et de céphalométrie ainsi que l’encadrement des chirurgiens dentistes inscrits au sein du DU d’orthodontie de la faculté de médecine dentaire – RABAT.
      Dans un souci permanent de formation continu, Dr AMGHAR a assisté à plusieurs séminaires et congrès nationaux et internationaux. Elle a participé aussi comme conférencière dans nombreux congrès et manifestations scientifiques.
      Le cabinet d’orthodontiste DR AMGHAR qui est situé à Rabat, vous offre des soins de qualité dans un cadre agréable. Le cabinet d’orthodontiste Dr AMGHAR vous accompagne pour des soins d’ortopédie dento-faciale ou ortodontie pour enfants, orthodontie de l’adulte.
      Composez le 05 22 86 23 22pour un rendez vous avec nos spécialistes
      Le cabinet d’orthodontiste Dr AMGHAR vous accompagne au quotidien pour une bonne santé buccale et des soins adaptés dans les spécialités : ortodontie et pédodontie. Toute notre équipe d’experts se tient prête à vous accueillir et à vous prodiguer les traitements les plus adaptés : pédodontie, orthodontie, esthétique dentaire, radiologie…
      Le cabinet d’orthodontiste Dr AMGHAR spécialisé dans l’orthodontie, est ouvert du lundi au vendredi 9H à 19H et le samedi de 9H à 13H.`,
    comment: `user {name} {value, plural,
    	  =0 {does not have any comments}
    	  =1 {has # comment}
    	  other {has # comments}
    	} (in real app this would be translated to French)`,
    HTMLComment: `user <b style='font-weight: bold'>{name} </b> {value, plural,
    	  =0 {does not have <i style='font-style: italic'>any</i> comments}
    	  =1 {has <i style='font-style: italic'>#</i> comment}
    	  other {has <i style='font-style: italic'>#</i> comments}
    	} (in real app this would be translated to French)`,
    nestedDateComment: `user {name} {value, plural,
  		  =0 {does not have any comments}
  		  =1 {has # comment}
  		  other {has # comments}
  		} as of {date} (in real app this would be translated to French)`,
    emptyCollectionMessage: 'No result found, try to insert a new {collection}.',
    appRights: '(C) 2018 tous droits réservés ',
  },
};
